/** Display translations only: provider IDs and saved matches remain unchanged. */
const countries: Record<string, string> = {
  Brazil: 'Brasil', England: 'Inglaterra', Spain: 'Espanha', Italy: 'Itália', Germany: 'Alemanha', France: 'França', Netherlands: 'Países Baixos', Belgium: 'Bélgica', Turkey: 'Turquia', Greece: 'Grécia', Scotland: 'Escócia', Wales: 'País de Gales', Ireland: 'Irlanda', 'Northern-Ireland': 'Irlanda do Norte', Switzerland: 'Suíça', Austria: 'Áustria', Denmark: 'Dinamarca', Sweden: 'Suécia', Norway: 'Noruega', Finland: 'Finlândia', Poland: 'Polônia', Ukraine: 'Ucrânia', Russia: 'Rússia', Romania: 'Romênia', Hungary: 'Hungria', Croatia: 'Croácia', Serbia: 'Sérvia', Czechia: 'Tchéquia', 'Czech-Republic': 'Tchéquia', Slovakia: 'Eslováquia', Slovenia: 'Eslovênia', Lithuania: 'Lituânia', Latvia: 'Letônia', Estonia: 'Estônia', Uruguay: 'Uruguai', Paraguay: 'Paraguai', Bolivia: 'Bolívia', Peru: 'Peru', Colombia: 'Colômbia', Ecuador: 'Equador', Mexico: 'México', USA: 'Estados Unidos', 'United-States': 'Estados Unidos', Canada: 'Canadá', Japan: 'Japão', China: 'China', 'South-Korea': 'Coreia do Sul', Australia: 'Austrália', 'Saudi-Arabia': 'Arábia Saudita', 'South-Africa': 'África do Sul', Morocco: 'Marrocos', Egypt: 'Egito', World: 'Internacional', Azerbaijan: 'Azerbaijão', Iceland: 'Islândia', Cyprus: 'Chipre', Israel: 'Israel', Georgia: 'Geórgia', Armenia: 'Armênia', 'United-Arab-Emirates': 'Emirados Árabes Unidos', Tunisia: 'Tunísia', Algeria: 'Argélia', 'Costa-Rica': 'Costa Rica', 'New-Zealand': 'Nova Zelândia', Albania: 'Albânia', Bulgaria: 'Bulgária', Belarus: 'Bielorrússia', Montenegro: 'Montenegro', 'Bosnia-and-Herzegovina': 'Bósnia e Herzegovina', 'North-Macedonia': 'Macedônia do Norte', 'El-Salvador': 'El Salvador', 'Dominican-Republic': 'República Dominicana', 'Trinidad-and-Tobago': 'Trinidad e Tobago', 'Hong-Kong': 'Hong Kong', 'Cape-Verde': 'Cabo Verde', 'Ivory-Coast': 'Costa do Marfim', Cameroon: 'Camarões', Nigeria: 'Nigéria', Ghana: 'Gana', Senegal: 'Senegal', Kenya: 'Quênia', Zambia: 'Zâmbia', Mozambique: 'Moçambique', 'Faroe-Islands': 'Ilhas Faroé', Malta: 'Malta', Luxembourg: 'Luxemburgo', 'Viet-Nam': 'Vietnã', Thailand: 'Tailândia', Indonesia: 'Indonésia', Malaysia: 'Malásia', Singapore: 'Singapura', India: 'Índia', Iran: 'Irã', Iraq: 'Iraque', Qatar: 'Catar', Kuwait: 'Kuwait', Bahrain: 'Bahrein', Jordan: 'Jordânia', Lebanon: 'Líbano', Palestine: 'Palestina', 'Sao-Tome-and-Principe': 'São Tomé e Príncipe', 'Equatorial-Guinea': 'Guiné Equatorial', 'Guinea-Bissau': 'Guiné-Bissau', Congo: 'Congo', 'DR-Congo': 'República Democrática do Congo'
};
export const countryLabel = (value: string) => countries[value] || value.replaceAll('-', ' ');
const exact: Record<string, string> = {
  'Match Winner': 'Resultado do jogo (1X2)', 'Home/Away': 'Vencedor (sem empate)', 'Double Chance': 'Dupla chance', 'Draw No Bet': 'Empate devolve', 'Asian Handicap': 'Handicap asiático', 'Goals Over/Under': 'Total de gols — mais/menos', 'Both Teams Score': 'Ambas marcam', 'Exact Score': 'Placar exato', 'Correct Score': 'Placar exato', 'HT/FT Double': 'Intervalo / final', 'Odd/Even': 'Par / ímpar', 'First Half Winner': 'Resultado do 1º tempo', 'Second Half Winner': 'Resultado do 2º tempo', 'Corners Over Under': 'Total de escanteios — mais/menos', 'Total - Home': 'Total do mandante', 'Total - Away': 'Total do visitante', 'Team To Score First': 'Primeira equipe a marcar', 'Team To Score Last': 'Última equipe a marcar', Home: 'Mandante', Away: 'Visitante', Draw: 'Empate', Yes: 'Sim', No: 'Não', None: 'Nenhuma', Odd: 'Ímpar', Even: 'Par', 'World Cup': 'Copa do Mundo', Friendlies: 'Amistosos', 'UEFA Nations League': 'Liga das Nações da UEFA'
};
export function footballLabel(value: string): string {
  if (exact[value]) return exact[value];
  return value.replace(/First Half|1st Half/gi, '1º tempo').replace(/Second Half|2nd Half/gi, '2º tempo').replace(/Regular Season/gi, 'Temporada regular').replace(/Quarter-finals/gi, 'Quartas de final').replace(/Semi-finals/gi, 'Semifinais').replace(/Round of 16/gi, 'Oitavas de final').replace(/Group Stage/gi, 'Fase de grupos').replace(/Finals/gi, 'Finais').replace(/Friendlies/gi, 'Amistosos').replace(/Qualification/gi, 'Eliminatórias').replace(/\bOver\b/gi, 'Mais de').replace(/\bUnder\b/gi, 'Menos de').replace(/\bCorners\b/gi, 'Escanteios').replace(/\bGoals\b/gi, 'Gols').replace(/\bCards\b/gi, 'Cartões').replace(/\bShots\b/gi, 'Chutes').replace(/\bHome\b/g, 'Mandante').replace(/\bAway\b/g, 'Visitante').replace(/\bDraw\b/g, 'Empate').replace(/\bWinner\b/gi, 'Vencedor').replace(/\bHandicap\s+Result\b/gi, 'Resultado com handicap').replace(/\bAsian\b/gi, 'Asiático').replace(/\bClean Sheet\b/gi, 'Sem sofrer gols').replace(/\bBoth Teams Score\b/gi, 'Ambas marcam').replace(/\bTo Score\b/gi, 'Para marcar').replace(/\bTotal\b/g, 'Total');
}
